### ISSUE TITLE
Resolve compatibility with LESS

### ISSUE THREAD

**Issue by adamkudrna** [visionappscz/stylelint-config-visionapps#4]
We are SCSS compatible, can we make it also for LESS?

**Comment by adamkudrna** [comment]
Yes!

**Comment by crishpeen** [comment]
In general, stylelint is compatible with SCSS, SugasSS and (experimentally) LESS. Everything depends on your implementation of stylelint to your workflow, because you might need third party parser and that could be problem.

However stylelint recommends these build tool plugins which shoud work without any troubles: https://github.com/stylelint/stylelint/blob/master/docs/user-guide/complementary-tools.md#build-tool-plugins
